# Generated by Django 5.2 on 2025-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(choices=[('Telecom', 'Telecom'), ('ICT', 'ICT'), ('Power', 'Power & Energy'), ('Support', 'Support Services')], default='ICT', max_length=50)),
            ],
        ),
    ]
