# Generated by Django 5.2 on 2025-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Untitled Project', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Telecom', 'Telecom'), ('ICT', 'ICT'), ('Power', 'Power & Energy'), ('Support', 'Support Services')], default='ICT', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
