# Generated by Django 5.2 on 2025-05-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_project_category_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Telecom', 'Telecom'), ('ICT', 'ICT'), ('Power', 'Power & Energy'), ('Support', 'Support Services')], default='ICT', max_length=50),
        ),
    ]
